services:
  crud:
    container_name: crud
    build: . 
    environment:
      PORT: 8080
      REDIS_URI: redis:6379
    ports:
      - "8080:8080"
    develop: 
      watch:
        - action: rebuild
          path: .
          target: /app
  redis:
    container_name: redis
    image: redis:latest