services:
  crud:
    container_name: crud
    build: . 
    ports:
      - "8080:8080"
    develop: 
      watch:
        - action: rebuild
          path: .
          target: /app
  db:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_URI: "mongodb://localhost:27017"
      DBNAME: "crud"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/postgresql/data

volumes:
  mongodata: {}