services:
  crud:
    container_name: crud
    build: . 
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017
      DBNAME_ENV: crud
    ports:
      - "8080:8080"
    develop: 
      watch:
        - action: rebuild
          path: .
          target: /app
  mongo:
    container_name: mongo
    image: mongo
    restart: always